config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'welcome/listing'

  resources :articles do
    get :autocomplete, on: :collection
    get :home, on: :collection
    resources :comments
  end

  resources :welcome, only: [:update, :destroy]

  root 'welcome#index'
  get 'search', to: 'search#search'

end

app/models/article.rb
require 'elasticsearch/model'
class Article < ActiveRecord::Base
  include Searchable
  has_many :images, :dependent => :destroy
  accepts_nested_attributes_for :images
  has_many :comments, dependent: :destroy
  belongs_to :user

  searchkick text_start: [:text]  
  def search_data
    attributes.merge(
      comment_body: comments.map(&:body)
      )
  end
end

Article.import

app/models/comment.rb
class Comment < ActiveRecord::Base
#  include Searchable
  belongs_to :article
  searchkick
end
#Comment.import

app/models/concerns/searchable.rb
module Searchable
  extend ActiveSupport::Concern

  included do
    include Elasticsearch::Model
    include Elasticsearch::Model::Callbacks

    after_commit on: [:create] do
      __elasticsearch__.index_document
    end

  end
end

app/models/image.rb
class Image < ActiveRecord::Base
  belongs_to :article
  has_attached_file :photo, styles: {
      thumb: "100x100#",
      small: "150x150>",
      medium: "200x200",
      large: "1024x768" }
  validates_attachment_presence :photo
  validates_attachment_size :photo, :less_than => 5.megabytes
  validates_attachment_content_type :photo, :content_type => ['image/jpeg', 'image/png']
end

app/models/role.rb
class Role < ActiveRecord::Base
  rolify :role_cname => 'User'
  has_and_belongs_to_many :users, :join_table => :users_roles

  belongs_to :resource,
             :polymorphic => true

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  after_create :assign_role_to_user
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :trackable, :validatable
  has_many :articles
  attr_accessor :role

  private

  def assign_role_to_user
    user = User.last
    user.add_role :"normal_user"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:password, :password_confirmation, :current_password, :email, :first_name, :last_name, :gender) }

    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:password, :password_confirmation, :current_password, :email, :first_name, :last_name, :gender) }
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  def index
    @articles = Article.all
  end

  def home
    @articles = current_user.articles
  end

  def new
    @article = Article.new
    @article.images.build
  end

  def create
    user = User.find(current_user.id)
    if user.articles.create(article_params)
      flash[:success] = 'Successfully published'
      redirect_to articles_path
    else
      flash[:danger] = 'Not published article'
      render 'new'
      #render :new
      #redirect_to new_article_path
    end
  end
  # for autocomplete
  def autocomplete
    render json: Article.search(params[:term], fields: [{text: :text_start}, :comment_body, :title], highlight: true, limit: 10).map(&:text)
  end

  def edit
    @article = Article.find(params[:id])
    @article.images.build
  end

  def update
    @article = Article.find(params[:id])
 
    if @article.update(article_params)
      flash[:success] = 'Article is updated'
      redirect_to @article
    else
      render 'edit'
    end
  end

  def destroy
    article = Article.find(params[:id])
    flash[:notice] = 'Successfully Destroyed'
    article.destroy
    redirect_to articles_path
  end

  def show
    @article = Article.find(params[:id])
  end

private
  def article_params
    params.require(:article).permit(:title, :text, :posted_on, :user_id, images_attributes: [:photo, :id, :caption, :photo_file_name, :_destroy])
  end
  
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
   
  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(comment_params)
    redirect_to article_path(@article)
  end

  def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @comment.destroy
    redirect_to article_path(@article)
  end
 
  private
    def comment_params
      params.require(:comment).permit(:commenter, :body)
    end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def search
    if params[:q].nil?
      @response = []
    else
      @response = Elasticsearch::Model.search params[:q]
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def listing
    @users = User.all
  end

  def update
    user = User.find(params[:id])
    role_name = params[:user][:role]
    user.add_role :"#{role_name}"
    redirect_to welcome_listing_path
  end

  def destroy
    user = User.find(params[:id])
    user.destroy
    redirect_to welcome_listing_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/shubh_helper.rb
module ShubhHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_article.html.erb
<p>
  <%= article.title %>
</p>  

app/views/articles/_form.html.erb
<link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
<script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
<script>
  $(function () {
    $( ".datepicker" ).datepicker({
      dateFormat: 'dd/mm/yy',
      minDate: '-1w',
      maxDate: '+1w'
    });
  });
</script>

<%= form_for @article, :html => { :multipart => true } do |f| %>
 <div class="row">

  <div class="form-group col-sm-3"> 
    <%= f.label (:title) %><br>
    <%= f.text_field :title, required: true, class: 'form-control' %>
  </div><br><br><br><br>
 
  <div class="form-group col-sm-3">
    <%= f.label :text %><br>
    <%= f.text_area :text, required: true, class: 'form-control' %>
  </div><br><br><br><br><br>

  <div class="form-group col-sm-3">
    <%= f.label :Will_Publish_on %><br>
    <%= f.text_field :posted_on, class: 'datepicker form-control', required: true %>
  </div><br><br><br><br>

  <div class="form-group col-sm-3">
    <% if @article.images.first.id == nil%>
      <%= f.fields_for :images do |ff|%>

        <%= ff.label :Image %><br>
        <%= ff.file_field :photo, class: "form-control", required: true %><br>
      <% end %>
    <% else %>
      <%= image_tag @article.images.first.photo.url(:small) %>
    <% end %>
  </div>

  </div><br><br><br><br>

  <div class="form-group col-sm-4">
    <%= f.submit 'Submit', class: 'btn btn-default' %>
  </div>
 </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Edit article</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', :back %>

app/views/articles/home.html.erb
<h1>My Articles</h1>
 
<table class="table">
  <tr >
    <th>Title</th>
    <th>Text</th>
    <th colspan="3"><center>Action</center></th>
  </tr>
 
  <% @articles.each do |article| %>
    <tr>
      <td><%= article.title %></td>
      <td><%= article.text %></td>
      <td><%= link_to 'show', article_path(article) %></td>
      <td><%= link_to 'Edit', edit_article_path(article) %></td>
      <td><%= link_to 'Destroy', article_path(article),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

app/views/articles/index.html.erb
<h1>Listing articles</h1>
 
<table class="table">
  <tr >
    <th>Title</th>
    <th>Text</th>
    <th colspan="3"><center>Action</center></th>
  </tr>
 
  <% @articles.each do |article| %>
    <tr>
      <td><%= article.title %></td>
      <td><%= article.text %></td>
      <td><%= link_to 'show', article_path(article) %></td>
      <td><%= link_to 'Edit', edit_article_path(article) %></td>
      <td><%= link_to 'Destroy', article_path(article),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

app/views/articles/new.html.erb
<h1>New article</h1>

<%= render 'form' %>
 
<%= link_to 'Back', :back %>

app/views/articles/show.html.erb
<dl>
  <p><kbd>Title:</kbd>->
  <%= @article.title %></p>

  <p><kbd>Text:</kbd>->
  <%= @article.text %></p>

  <p><kbd>Posted Date:</kbd>
  -><%= @article.posted_on %></p>

  <dt><kbd>Photo:</kbd></dt>
  <% if @article.images.present? %>
    <%= image_tag @article.images.last.photo.url(:small) %>
  <% end %>
</dl>

<h2>Comments</h2>
<%= render @article.comments %>
 
<h2>Add a comment:</h2>
<%= render 'comments/form' %>
 
<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', :back %>

app/views/comments/_comment.html.erb
<p>
  <strong>Commenter:</strong>
  <%= comment.commenter %>
</p>
 
<p>
  <strong>Comment:</strong>
  <%= comment.body %>
</p>

<p>
  <%= link_to 'Destroy Comment', [comment.article, comment],
               method: :delete,
               data: { confirm: 'Are you sure?' } %>
</p>

app/views/comments/_form.html.erb
<%= form_for([@article, @article.comments.build]) do |f| %>
  <p>
    <%= f.label :commenter %><br>
    <%= f.text_field :commenter %>
  </p>
  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/layouts/_messages.html.erb
<script type="text/javascript">
$(document).ready(function(){
  setTimeout(function(){
    $('#flash').fadeOut();
  }, 2000);
 })
</script>

<% flash.each do |key, value| %>
<div id="flash">
  <div class="alert alert-<%= key %>">
    <ul>
      <li>
        <%= value %>
        <a href="#" data-dismiss="alert" class="close">×</a>
      </li>
    </ul>
    </div>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <script src="//code.jquery.com/jquery-1.10.2.js"></script>
  <script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>

</head>

<body>
<%= render 'layouts/messages' %>
<%= yield %>

<% if user_signed_in? %>
  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <div class="navbar-header">
        <%= link_to 'Home', root_path ,class: "navbar-brand" %>
      </div>
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <% if current_user.has_role? :admin %>
            <li><%= link_to 'Article\'s Index', articles_path %></li>
          <% end %>
          <li><%= link_to 'Create New article', new_article_path %></li>
          <li>
            <form class="navbar-form navbar-left" role="search">
              <div class="form-group">
                <input type="text" id="query" class="form-control" placeholder="Search">
              </div>
            </form>
          </li>
          <li> <%= link_to "Search", search_path %></li>
          <li> <%= link_to "My Article", home_articles_path %></li>
          <% if current_user.has_role? :admin %>
            <li><%= link_to 'Assign Role', welcome_listing_path  %></li>
          <% end %>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <li> <%= link_to "Edit Profile", edit_user_registration_path %></li>
          <li><%= link_to "Sign out", destroy_user_session_path, class: "navbar-brand", :method => :delete %></li>
        </ul>
      </div>
    </div>
  </nav>

<% end %>

</body>
</html>

<script>
  $(function() {
    $("#query").autocomplete({
      source: "/articles/autocomplete"
    });
  });
</script>

app/views/search/search.html.erb
<style type="text/css">
  em {
  background: yellow;
}
</style>

<h1>Articles Search</h1>

<%= form_for search_path, method: :get do |f| %>
  <p>
    <%= f.label "Search for" %>
    <%= text_field_tag :q, params[:q] %>
    <%= submit_tag "Go", name: nil %>
  </p>
<% end %>

<ul>
  <% @response.each do |article| %>
    <% if article.type == "article" %>
      <li>
        <h3>
          <%= link_to article.try(:highlight).try(:title) ? article.highlight.title[0].html_safe : article.title,
            controller: "articles",
            action: "show",
            id: article._id%>
        </h3>
        <% if article.try(:highlight).try(:text) %>
          <% article.highlight.text.each do |snippet| %>
            <p><%= snippet.html_safe %>...</p>
          <% end %>
        <% end %>
      </li>
    <% end %>
  <% end %>
</ul>

<p>Commenter:</p>
<ul>
  <% @response.each do |article| %>
    <% if article.type == "comment" %>
      <li>
        <h3>
          <%= link_to article.try(:highlight).try(:commenter) ? article.highlight.commenter[0].html_safe : article.commenter,
            controller: "articles",
            action: "show",
            id: article._id%>
        </h3>
        <% if article.try(:highlight).try(:body) %>
          <% article.highlight.body.each do |snippet| %>
            <p><%= snippet.html_safe %>...</p>
          <% end %>
        <% end %>
      </li>
    <% end %>
  <% end %>
</ul>

<%= link_to 'Back', articles_path %>

app/views/welcome/index.html.erb
<h1>Welcome to Blog </h1>

app/views/welcome/listing.html.erb
<h1>All Users</h1>
 
<table class="table">
  <tr >
    <th>Name</th>
    <th>Email</th>
    <th>Role</th>
    <th><center>Action</center></th>
  </tr>
 
  <% @users.each do |user| %>
    <tr>
      <td><%= user.first_name.concat(user.last_name) %></td>
      <td><%= user.email %></td>
      <%= form_for user, url: welcome_path(user.id) do |f| %>
        <td><%= f.select :role,options_for_select(Role.all.pluck(:name), selected: user.roles.last.name)  %></td>
        <td><%= f.submit 'Update' %> <%= link_to "", welcome_path(user.id),  class: 'glyphicon glyphicon-trash', method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>

    </tr>
  <% end %>
</table>